title: Python install options
hero_image: images/banner.png
description: Guidance about what options you have for using Python 
version: 4
listed: false
copyedit: false
last_tested: "2020-06-09"
steps:
  - title: Introduction
  - title: Online
  - title: Dedicated Python editor
  - title: Full Python install
